#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="turismo_seguro")]
	public partial class DbLibraryEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttd_cotizacion(td_cotizacion instance);
    partial void Updatetd_cotizacion(td_cotizacion instance);
    partial void Deletetd_cotizacion(td_cotizacion instance);
    partial void Inserttm_usuario(tm_usuario instance);
    partial void Updatetm_usuario(tm_usuario instance);
    partial void Deletetm_usuario(tm_usuario instance);
    partial void Inserttd_pago(td_pago instance);
    partial void Updatetd_pago(td_pago instance);
    partial void Deletetd_pago(td_pago instance);
    partial void Inserttd_poliza(td_poliza instance);
    partial void Updatetd_poliza(td_poliza instance);
    partial void Deletetd_poliza(td_poliza instance);
    partial void Inserttd_reclamo(td_reclamo instance);
    partial void Updatetd_reclamo(td_reclamo instance);
    partial void Deletetd_reclamo(td_reclamo instance);
    partial void Inserttd_viajero(td_viajero instance);
    partial void Updatetd_viajero(td_viajero instance);
    partial void Deletetd_viajero(td_viajero instance);
    partial void Inserttm_moneda(tm_moneda instance);
    partial void Updatetm_moneda(tm_moneda instance);
    partial void Deletetm_moneda(tm_moneda instance);
    partial void Inserttm_pai(tm_pai instance);
    partial void Updatetm_pai(tm_pai instance);
    partial void Deletetm_pai(tm_pai instance);
    partial void Inserttm_seguro(tm_seguro instance);
    partial void Updatetm_seguro(tm_seguro instance);
    partial void Deletetm_seguro(tm_seguro instance);
    #endregion
		
		public DbLibraryEntityDataContext() : 
				base(global::capaDatos.Properties.Settings.Default.turismo_seguroConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<td_cotizacion> td_cotizacions
		{
			get
			{
				return this.GetTable<td_cotizacion>();
			}
		}
		
		public System.Data.Linq.Table<tm_usuario> tm_usuarios
		{
			get
			{
				return this.GetTable<tm_usuario>();
			}
		}
		
		public System.Data.Linq.Table<td_pago> td_pagos
		{
			get
			{
				return this.GetTable<td_pago>();
			}
		}
		
		public System.Data.Linq.Table<td_poliza> td_polizas
		{
			get
			{
				return this.GetTable<td_poliza>();
			}
		}
		
		public System.Data.Linq.Table<td_reclamo> td_reclamos
		{
			get
			{
				return this.GetTable<td_reclamo>();
			}
		}
		
		public System.Data.Linq.Table<td_viajero> td_viajeros
		{
			get
			{
				return this.GetTable<td_viajero>();
			}
		}
		
		public System.Data.Linq.Table<tm_moneda> tm_monedas
		{
			get
			{
				return this.GetTable<tm_moneda>();
			}
		}
		
		public System.Data.Linq.Table<tm_pai> tm_pais
		{
			get
			{
				return this.GetTable<tm_pai>();
			}
		}
		
		public System.Data.Linq.Table<tm_seguro> tm_seguros
		{
			get
			{
				return this.GetTable<tm_seguro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.td_cotizacion")]
	public partial class td_cotizacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cotizacion;
		
		private int _id_usuario;
		
		private int _id_seguro;
		
		private int _id_pais_destino;
		
		private int _id_moneda;
		
		private System.DateTime _fecha_salida;
		
		private System.DateTime _fecha_regreso;
		
		private int _cantidad_viajeros;
		
		private decimal _precio_total;
		
		private string _estado;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntitySet<td_poliza> _td_polizas;
		
		private EntitySet<td_viajero> _td_viajeros;
		
		private EntityRef<tm_usuario> _tm_usuario;
		
		private EntityRef<tm_moneda> _tm_moneda;
		
		private EntityRef<tm_pai> _tm_pai;
		
		private EntityRef<tm_seguro> _tm_seguro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cotizacionChanging(int value);
    partial void Onid_cotizacionChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_seguroChanging(int value);
    partial void Onid_seguroChanged();
    partial void Onid_pais_destinoChanging(int value);
    partial void Onid_pais_destinoChanged();
    partial void Onid_monedaChanging(int value);
    partial void Onid_monedaChanged();
    partial void Onfecha_salidaChanging(System.DateTime value);
    partial void Onfecha_salidaChanged();
    partial void Onfecha_regresoChanging(System.DateTime value);
    partial void Onfecha_regresoChanged();
    partial void Oncantidad_viajerosChanging(int value);
    partial void Oncantidad_viajerosChanged();
    partial void Onprecio_totalChanging(decimal value);
    partial void Onprecio_totalChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public td_cotizacion()
		{
			this._td_polizas = new EntitySet<td_poliza>(new Action<td_poliza>(this.attach_td_polizas), new Action<td_poliza>(this.detach_td_polizas));
			this._td_viajeros = new EntitySet<td_viajero>(new Action<td_viajero>(this.attach_td_viajeros), new Action<td_viajero>(this.detach_td_viajeros));
			this._tm_usuario = default(EntityRef<tm_usuario>);
			this._tm_moneda = default(EntityRef<tm_moneda>);
			this._tm_pai = default(EntityRef<tm_pai>);
			this._tm_seguro = default(EntityRef<tm_seguro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cotizacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cotizacion
		{
			get
			{
				return this._id_cotizacion;
			}
			set
			{
				if ((this._id_cotizacion != value))
				{
					this.Onid_cotizacionChanging(value);
					this.SendPropertyChanging();
					this._id_cotizacion = value;
					this.SendPropertyChanged("id_cotizacion");
					this.Onid_cotizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._tm_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_seguro", DbType="Int NOT NULL")]
		public int id_seguro
		{
			get
			{
				return this._id_seguro;
			}
			set
			{
				if ((this._id_seguro != value))
				{
					if (this._tm_seguro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_seguroChanging(value);
					this.SendPropertyChanging();
					this._id_seguro = value;
					this.SendPropertyChanged("id_seguro");
					this.Onid_seguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pais_destino", DbType="Int NOT NULL")]
		public int id_pais_destino
		{
			get
			{
				return this._id_pais_destino;
			}
			set
			{
				if ((this._id_pais_destino != value))
				{
					if (this._tm_pai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pais_destinoChanging(value);
					this.SendPropertyChanging();
					this._id_pais_destino = value;
					this.SendPropertyChanged("id_pais_destino");
					this.Onid_pais_destinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_moneda", DbType="Int NOT NULL")]
		public int id_moneda
		{
			get
			{
				return this._id_moneda;
			}
			set
			{
				if ((this._id_moneda != value))
				{
					if (this._tm_moneda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_monedaChanging(value);
					this.SendPropertyChanging();
					this._id_moneda = value;
					this.SendPropertyChanged("id_moneda");
					this.Onid_monedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_salida", DbType="Date NOT NULL")]
		public System.DateTime fecha_salida
		{
			get
			{
				return this._fecha_salida;
			}
			set
			{
				if ((this._fecha_salida != value))
				{
					this.Onfecha_salidaChanging(value);
					this.SendPropertyChanging();
					this._fecha_salida = value;
					this.SendPropertyChanged("fecha_salida");
					this.Onfecha_salidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_regreso", DbType="Date NOT NULL")]
		public System.DateTime fecha_regreso
		{
			get
			{
				return this._fecha_regreso;
			}
			set
			{
				if ((this._fecha_regreso != value))
				{
					this.Onfecha_regresoChanging(value);
					this.SendPropertyChanging();
					this._fecha_regreso = value;
					this.SendPropertyChanged("fecha_regreso");
					this.Onfecha_regresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad_viajeros", DbType="Int NOT NULL")]
		public int cantidad_viajeros
		{
			get
			{
				return this._cantidad_viajeros;
			}
			set
			{
				if ((this._cantidad_viajeros != value))
				{
					this.Oncantidad_viajerosChanging(value);
					this.SendPropertyChanging();
					this._cantidad_viajeros = value;
					this.SendPropertyChanged("cantidad_viajeros");
					this.Oncantidad_viajerosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_total", DbType="Decimal(10,2) NOT NULL")]
		public decimal precio_total
		{
			get
			{
				return this._precio_total;
			}
			set
			{
				if ((this._precio_total != value))
				{
					this.Onprecio_totalChanging(value);
					this.SendPropertyChanging();
					this._precio_total = value;
					this.SendPropertyChanged("precio_total");
					this.Onprecio_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(20)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_cotizacion_td_poliza", Storage="_td_polizas", ThisKey="id_cotizacion", OtherKey="id_cotizacion")]
		public EntitySet<td_poliza> td_polizas
		{
			get
			{
				return this._td_polizas;
			}
			set
			{
				this._td_polizas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_cotizacion_td_viajero", Storage="_td_viajeros", ThisKey="id_cotizacion", OtherKey="id_cotizacion")]
		public EntitySet<td_viajero> td_viajeros
		{
			get
			{
				return this._td_viajeros;
			}
			set
			{
				this._td_viajeros.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_cotizacion", Storage="_tm_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tm_usuario tm_usuario
		{
			get
			{
				return this._tm_usuario.Entity;
			}
			set
			{
				tm_usuario previousValue = this._tm_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tm_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_usuario.Entity = null;
						previousValue.td_cotizacions.Remove(this);
					}
					this._tm_usuario.Entity = value;
					if ((value != null))
					{
						value.td_cotizacions.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("tm_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_moneda_td_cotizacion", Storage="_tm_moneda", ThisKey="id_moneda", OtherKey="id_moneda", IsForeignKey=true)]
		public tm_moneda tm_moneda
		{
			get
			{
				return this._tm_moneda.Entity;
			}
			set
			{
				tm_moneda previousValue = this._tm_moneda.Entity;
				if (((previousValue != value) 
							|| (this._tm_moneda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_moneda.Entity = null;
						previousValue.td_cotizacions.Remove(this);
					}
					this._tm_moneda.Entity = value;
					if ((value != null))
					{
						value.td_cotizacions.Add(this);
						this._id_moneda = value.id_moneda;
					}
					else
					{
						this._id_moneda = default(int);
					}
					this.SendPropertyChanged("tm_moneda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_pai_td_cotizacion", Storage="_tm_pai", ThisKey="id_pais_destino", OtherKey="id_pais", IsForeignKey=true)]
		public tm_pai tm_pai
		{
			get
			{
				return this._tm_pai.Entity;
			}
			set
			{
				tm_pai previousValue = this._tm_pai.Entity;
				if (((previousValue != value) 
							|| (this._tm_pai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_pai.Entity = null;
						previousValue.td_cotizacions.Remove(this);
					}
					this._tm_pai.Entity = value;
					if ((value != null))
					{
						value.td_cotizacions.Add(this);
						this._id_pais_destino = value.id_pais;
					}
					else
					{
						this._id_pais_destino = default(int);
					}
					this.SendPropertyChanged("tm_pai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_seguro_td_cotizacion", Storage="_tm_seguro", ThisKey="id_seguro", OtherKey="id_seguro", IsForeignKey=true)]
		public tm_seguro tm_seguro
		{
			get
			{
				return this._tm_seguro.Entity;
			}
			set
			{
				tm_seguro previousValue = this._tm_seguro.Entity;
				if (((previousValue != value) 
							|| (this._tm_seguro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_seguro.Entity = null;
						previousValue.td_cotizacions.Remove(this);
					}
					this._tm_seguro.Entity = value;
					if ((value != null))
					{
						value.td_cotizacions.Add(this);
						this._id_seguro = value.id_seguro;
					}
					else
					{
						this._id_seguro = default(int);
					}
					this.SendPropertyChanged("tm_seguro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_td_polizas(td_poliza entity)
		{
			this.SendPropertyChanging();
			entity.td_cotizacion = this;
		}
		
		private void detach_td_polizas(td_poliza entity)
		{
			this.SendPropertyChanging();
			entity.td_cotizacion = null;
		}
		
		private void attach_td_viajeros(td_viajero entity)
		{
			this.SendPropertyChanging();
			entity.td_cotizacion = this;
		}
		
		private void detach_td_viajeros(td_viajero entity)
		{
			this.SendPropertyChanging();
			entity.td_cotizacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tm_usuario")]
	public partial class tm_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nombre;
		
		private string _correo;
		
		private string _telefono;
		
		private string _contraseña;
		
		private string _tipo_usuario;
		
		private string _direccion;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntitySet<td_cotizacion> _td_cotizacions;
		
		private EntitySet<td_pago> _td_pagos;
		
		private EntitySet<td_poliza> _td_polizas;
		
		private EntitySet<td_reclamo> _td_reclamos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void Ontipo_usuarioChanging(string value);
    partial void Ontipo_usuarioChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public tm_usuario()
		{
			this._td_cotizacions = new EntitySet<td_cotizacion>(new Action<td_cotizacion>(this.attach_td_cotizacions), new Action<td_cotizacion>(this.detach_td_cotizacions));
			this._td_pagos = new EntitySet<td_pago>(new Action<td_pago>(this.attach_td_pagos), new Action<td_pago>(this.detach_td_pagos));
			this._td_polizas = new EntitySet<td_poliza>(new Action<td_poliza>(this.attach_td_polizas), new Action<td_poliza>(this.detach_td_polizas));
			this._td_reclamos = new EntitySet<td_reclamo>(new Action<td_reclamo>(this.attach_td_reclamos), new Action<td_reclamo>(this.detach_td_reclamos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tipo_usuario
		{
			get
			{
				return this._tipo_usuario;
			}
			set
			{
				if ((this._tipo_usuario != value))
				{
					this.Ontipo_usuarioChanging(value);
					this.SendPropertyChanging();
					this._tipo_usuario = value;
					this.SendPropertyChanged("tipo_usuario");
					this.Ontipo_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_cotizacion", Storage="_td_cotizacions", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<td_cotizacion> td_cotizacions
		{
			get
			{
				return this._td_cotizacions;
			}
			set
			{
				this._td_cotizacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_pago", Storage="_td_pagos", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<td_pago> td_pagos
		{
			get
			{
				return this._td_pagos;
			}
			set
			{
				this._td_pagos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_poliza", Storage="_td_polizas", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<td_poliza> td_polizas
		{
			get
			{
				return this._td_polizas;
			}
			set
			{
				this._td_polizas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_reclamo", Storage="_td_reclamos", ThisKey="id_usuario", OtherKey="id_usuario")]
		public EntitySet<td_reclamo> td_reclamos
		{
			get
			{
				return this._td_reclamos;
			}
			set
			{
				this._td_reclamos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = this;
		}
		
		private void detach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = null;
		}
		
		private void attach_td_pagos(td_pago entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = this;
		}
		
		private void detach_td_pagos(td_pago entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = null;
		}
		
		private void attach_td_polizas(td_poliza entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = this;
		}
		
		private void detach_td_polizas(td_poliza entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = null;
		}
		
		private void attach_td_reclamos(td_reclamo entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = this;
		}
		
		private void detach_td_reclamos(td_reclamo entity)
		{
			this.SendPropertyChanging();
			entity.tm_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.td_pago")]
	public partial class td_pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pago;
		
		private int _id_usuario;
		
		private int _id_poliza;
		
		private int _id_moneda;
		
		private decimal _monto_pagado;
		
		private string _metodo_pago;
		
		private string _referencia_pago;
		
		private string _estado;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntityRef<tm_usuario> _tm_usuario;
		
		private EntityRef<td_poliza> _td_poliza;
		
		private EntityRef<tm_moneda> _tm_moneda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pagoChanging(int value);
    partial void Onid_pagoChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_polizaChanging(int value);
    partial void Onid_polizaChanged();
    partial void Onid_monedaChanging(int value);
    partial void Onid_monedaChanged();
    partial void Onmonto_pagadoChanging(decimal value);
    partial void Onmonto_pagadoChanged();
    partial void Onmetodo_pagoChanging(string value);
    partial void Onmetodo_pagoChanged();
    partial void Onreferencia_pagoChanging(string value);
    partial void Onreferencia_pagoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public td_pago()
		{
			this._tm_usuario = default(EntityRef<tm_usuario>);
			this._td_poliza = default(EntityRef<td_poliza>);
			this._tm_moneda = default(EntityRef<tm_moneda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pago
		{
			get
			{
				return this._id_pago;
			}
			set
			{
				if ((this._id_pago != value))
				{
					this.Onid_pagoChanging(value);
					this.SendPropertyChanging();
					this._id_pago = value;
					this.SendPropertyChanged("id_pago");
					this.Onid_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._tm_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_poliza", DbType="Int NOT NULL")]
		public int id_poliza
		{
			get
			{
				return this._id_poliza;
			}
			set
			{
				if ((this._id_poliza != value))
				{
					if (this._td_poliza.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_polizaChanging(value);
					this.SendPropertyChanging();
					this._id_poliza = value;
					this.SendPropertyChanged("id_poliza");
					this.Onid_polizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_moneda", DbType="Int NOT NULL")]
		public int id_moneda
		{
			get
			{
				return this._id_moneda;
			}
			set
			{
				if ((this._id_moneda != value))
				{
					if (this._tm_moneda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_monedaChanging(value);
					this.SendPropertyChanging();
					this._id_moneda = value;
					this.SendPropertyChanged("id_moneda");
					this.Onid_monedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_pagado", DbType="Decimal(10,2) NOT NULL")]
		public decimal monto_pagado
		{
			get
			{
				return this._monto_pagado;
			}
			set
			{
				if ((this._monto_pagado != value))
				{
					this.Onmonto_pagadoChanging(value);
					this.SendPropertyChanging();
					this._monto_pagado = value;
					this.SendPropertyChanged("monto_pagado");
					this.Onmonto_pagadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metodo_pago", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string metodo_pago
		{
			get
			{
				return this._metodo_pago;
			}
			set
			{
				if ((this._metodo_pago != value))
				{
					this.Onmetodo_pagoChanging(value);
					this.SendPropertyChanging();
					this._metodo_pago = value;
					this.SendPropertyChanged("metodo_pago");
					this.Onmetodo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_pago", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string referencia_pago
		{
			get
			{
				return this._referencia_pago;
			}
			set
			{
				if ((this._referencia_pago != value))
				{
					this.Onreferencia_pagoChanging(value);
					this.SendPropertyChanging();
					this._referencia_pago = value;
					this.SendPropertyChanged("referencia_pago");
					this.Onreferencia_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(20)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_pago", Storage="_tm_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tm_usuario tm_usuario
		{
			get
			{
				return this._tm_usuario.Entity;
			}
			set
			{
				tm_usuario previousValue = this._tm_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tm_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_usuario.Entity = null;
						previousValue.td_pagos.Remove(this);
					}
					this._tm_usuario.Entity = value;
					if ((value != null))
					{
						value.td_pagos.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("tm_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_poliza_td_pago", Storage="_td_poliza", ThisKey="id_poliza", OtherKey="id_poliza", IsForeignKey=true)]
		public td_poliza td_poliza
		{
			get
			{
				return this._td_poliza.Entity;
			}
			set
			{
				td_poliza previousValue = this._td_poliza.Entity;
				if (((previousValue != value) 
							|| (this._td_poliza.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._td_poliza.Entity = null;
						previousValue.td_pagos.Remove(this);
					}
					this._td_poliza.Entity = value;
					if ((value != null))
					{
						value.td_pagos.Add(this);
						this._id_poliza = value.id_poliza;
					}
					else
					{
						this._id_poliza = default(int);
					}
					this.SendPropertyChanged("td_poliza");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_moneda_td_pago", Storage="_tm_moneda", ThisKey="id_moneda", OtherKey="id_moneda", IsForeignKey=true)]
		public tm_moneda tm_moneda
		{
			get
			{
				return this._tm_moneda.Entity;
			}
			set
			{
				tm_moneda previousValue = this._tm_moneda.Entity;
				if (((previousValue != value) 
							|| (this._tm_moneda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_moneda.Entity = null;
						previousValue.td_pagos.Remove(this);
					}
					this._tm_moneda.Entity = value;
					if ((value != null))
					{
						value.td_pagos.Add(this);
						this._id_moneda = value.id_moneda;
					}
					else
					{
						this._id_moneda = default(int);
					}
					this.SendPropertyChanged("tm_moneda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.td_poliza")]
	public partial class td_poliza : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_poliza;
		
		private int _id_usuario;
		
		private int _id_seguro;
		
		private int _id_cotizacion;
		
		private System.DateTime _fecha_inicio;
		
		private System.DateTime _fecha_fin;
		
		private decimal _monto;
		
		private string _estado;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntitySet<td_pago> _td_pagos;
		
		private EntitySet<td_reclamo> _td_reclamos;
		
		private EntityRef<td_cotizacion> _td_cotizacion;
		
		private EntityRef<tm_usuario> _tm_usuario;
		
		private EntityRef<tm_seguro> _tm_seguro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_polizaChanging(int value);
    partial void Onid_polizaChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onid_seguroChanging(int value);
    partial void Onid_seguroChanged();
    partial void Onid_cotizacionChanging(int value);
    partial void Onid_cotizacionChanged();
    partial void Onfecha_inicioChanging(System.DateTime value);
    partial void Onfecha_inicioChanged();
    partial void Onfecha_finChanging(System.DateTime value);
    partial void Onfecha_finChanged();
    partial void OnmontoChanging(decimal value);
    partial void OnmontoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public td_poliza()
		{
			this._td_pagos = new EntitySet<td_pago>(new Action<td_pago>(this.attach_td_pagos), new Action<td_pago>(this.detach_td_pagos));
			this._td_reclamos = new EntitySet<td_reclamo>(new Action<td_reclamo>(this.attach_td_reclamos), new Action<td_reclamo>(this.detach_td_reclamos));
			this._td_cotizacion = default(EntityRef<td_cotizacion>);
			this._tm_usuario = default(EntityRef<tm_usuario>);
			this._tm_seguro = default(EntityRef<tm_seguro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_poliza", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_poliza
		{
			get
			{
				return this._id_poliza;
			}
			set
			{
				if ((this._id_poliza != value))
				{
					this.Onid_polizaChanging(value);
					this.SendPropertyChanging();
					this._id_poliza = value;
					this.SendPropertyChanged("id_poliza");
					this.Onid_polizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._tm_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_seguro", DbType="Int NOT NULL")]
		public int id_seguro
		{
			get
			{
				return this._id_seguro;
			}
			set
			{
				if ((this._id_seguro != value))
				{
					if (this._tm_seguro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_seguroChanging(value);
					this.SendPropertyChanging();
					this._id_seguro = value;
					this.SendPropertyChanged("id_seguro");
					this.Onid_seguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cotizacion", DbType="Int NOT NULL")]
		public int id_cotizacion
		{
			get
			{
				return this._id_cotizacion;
			}
			set
			{
				if ((this._id_cotizacion != value))
				{
					if (this._td_cotizacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cotizacionChanging(value);
					this.SendPropertyChanging();
					this._id_cotizacion = value;
					this.SendPropertyChanged("id_cotizacion");
					this.Onid_cotizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio", DbType="Date NOT NULL")]
		public System.DateTime fecha_inicio
		{
			get
			{
				return this._fecha_inicio;
			}
			set
			{
				if ((this._fecha_inicio != value))
				{
					this.Onfecha_inicioChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio = value;
					this.SendPropertyChanged("fecha_inicio");
					this.Onfecha_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_fin", DbType="Date NOT NULL")]
		public System.DateTime fecha_fin
		{
			get
			{
				return this._fecha_fin;
			}
			set
			{
				if ((this._fecha_fin != value))
				{
					this.Onfecha_finChanging(value);
					this.SendPropertyChanging();
					this._fecha_fin = value;
					this.SendPropertyChanged("fecha_fin");
					this.Onfecha_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Decimal(10,2) NOT NULL")]
		public decimal monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(20)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_poliza_td_pago", Storage="_td_pagos", ThisKey="id_poliza", OtherKey="id_poliza")]
		public EntitySet<td_pago> td_pagos
		{
			get
			{
				return this._td_pagos;
			}
			set
			{
				this._td_pagos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_poliza_td_reclamo", Storage="_td_reclamos", ThisKey="id_poliza", OtherKey="id_poliza")]
		public EntitySet<td_reclamo> td_reclamos
		{
			get
			{
				return this._td_reclamos;
			}
			set
			{
				this._td_reclamos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_cotizacion_td_poliza", Storage="_td_cotizacion", ThisKey="id_cotizacion", OtherKey="id_cotizacion", IsForeignKey=true)]
		public td_cotizacion td_cotizacion
		{
			get
			{
				return this._td_cotizacion.Entity;
			}
			set
			{
				td_cotizacion previousValue = this._td_cotizacion.Entity;
				if (((previousValue != value) 
							|| (this._td_cotizacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._td_cotizacion.Entity = null;
						previousValue.td_polizas.Remove(this);
					}
					this._td_cotizacion.Entity = value;
					if ((value != null))
					{
						value.td_polizas.Add(this);
						this._id_cotizacion = value.id_cotizacion;
					}
					else
					{
						this._id_cotizacion = default(int);
					}
					this.SendPropertyChanged("td_cotizacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_poliza", Storage="_tm_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tm_usuario tm_usuario
		{
			get
			{
				return this._tm_usuario.Entity;
			}
			set
			{
				tm_usuario previousValue = this._tm_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tm_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_usuario.Entity = null;
						previousValue.td_polizas.Remove(this);
					}
					this._tm_usuario.Entity = value;
					if ((value != null))
					{
						value.td_polizas.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("tm_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_seguro_td_poliza", Storage="_tm_seguro", ThisKey="id_seguro", OtherKey="id_seguro", IsForeignKey=true)]
		public tm_seguro tm_seguro
		{
			get
			{
				return this._tm_seguro.Entity;
			}
			set
			{
				tm_seguro previousValue = this._tm_seguro.Entity;
				if (((previousValue != value) 
							|| (this._tm_seguro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_seguro.Entity = null;
						previousValue.td_polizas.Remove(this);
					}
					this._tm_seguro.Entity = value;
					if ((value != null))
					{
						value.td_polizas.Add(this);
						this._id_seguro = value.id_seguro;
					}
					else
					{
						this._id_seguro = default(int);
					}
					this.SendPropertyChanged("tm_seguro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_td_pagos(td_pago entity)
		{
			this.SendPropertyChanging();
			entity.td_poliza = this;
		}
		
		private void detach_td_pagos(td_pago entity)
		{
			this.SendPropertyChanging();
			entity.td_poliza = null;
		}
		
		private void attach_td_reclamos(td_reclamo entity)
		{
			this.SendPropertyChanging();
			entity.td_poliza = this;
		}
		
		private void detach_td_reclamos(td_reclamo entity)
		{
			this.SendPropertyChanging();
			entity.td_poliza = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.td_reclamo")]
	public partial class td_reclamo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_reclamo;
		
		private int _id_poliza;
		
		private int _id_usuario;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_reclamo;
		
		private string _estado;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntityRef<td_poliza> _td_poliza;
		
		private EntityRef<tm_usuario> _tm_usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_reclamoChanging(int value);
    partial void Onid_reclamoChanged();
    partial void Onid_polizaChanging(int value);
    partial void Onid_polizaChanged();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_reclamoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_reclamoChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public td_reclamo()
		{
			this._td_poliza = default(EntityRef<td_poliza>);
			this._tm_usuario = default(EntityRef<tm_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_reclamo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_reclamo
		{
			get
			{
				return this._id_reclamo;
			}
			set
			{
				if ((this._id_reclamo != value))
				{
					this.Onid_reclamoChanging(value);
					this.SendPropertyChanging();
					this._id_reclamo = value;
					this.SendPropertyChanged("id_reclamo");
					this.Onid_reclamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_poliza", DbType="Int NOT NULL")]
		public int id_poliza
		{
			get
			{
				return this._id_poliza;
			}
			set
			{
				if ((this._id_poliza != value))
				{
					if (this._td_poliza.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_polizaChanging(value);
					this.SendPropertyChanging();
					this._id_poliza = value;
					this.SendPropertyChanged("id_poliza");
					this.Onid_polizaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="Int NOT NULL")]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					if (this._tm_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_reclamo", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_reclamo
		{
			get
			{
				return this._fecha_reclamo;
			}
			set
			{
				if ((this._fecha_reclamo != value))
				{
					this.Onfecha_reclamoChanging(value);
					this.SendPropertyChanging();
					this._fecha_reclamo = value;
					this.SendPropertyChanged("fecha_reclamo");
					this.Onfecha_reclamoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(20)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_poliza_td_reclamo", Storage="_td_poliza", ThisKey="id_poliza", OtherKey="id_poliza", IsForeignKey=true)]
		public td_poliza td_poliza
		{
			get
			{
				return this._td_poliza.Entity;
			}
			set
			{
				td_poliza previousValue = this._td_poliza.Entity;
				if (((previousValue != value) 
							|| (this._td_poliza.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._td_poliza.Entity = null;
						previousValue.td_reclamos.Remove(this);
					}
					this._td_poliza.Entity = value;
					if ((value != null))
					{
						value.td_reclamos.Add(this);
						this._id_poliza = value.id_poliza;
					}
					else
					{
						this._id_poliza = default(int);
					}
					this.SendPropertyChanged("td_poliza");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_usuario_td_reclamo", Storage="_tm_usuario", ThisKey="id_usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tm_usuario tm_usuario
		{
			get
			{
				return this._tm_usuario.Entity;
			}
			set
			{
				tm_usuario previousValue = this._tm_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tm_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tm_usuario.Entity = null;
						previousValue.td_reclamos.Remove(this);
					}
					this._tm_usuario.Entity = value;
					if ((value != null))
					{
						value.td_reclamos.Add(this);
						this._id_usuario = value.id_usuario;
					}
					else
					{
						this._id_usuario = default(int);
					}
					this.SendPropertyChanged("tm_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.td_viajero")]
	public partial class td_viajero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_viajero;
		
		private int _id_cotizacion;
		
		private string _nombre;
		
		private string _cedula_pasaporte;
		
		private int _edad;
		
		private string _telefono;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntityRef<td_cotizacion> _td_cotizacion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_viajeroChanging(int value);
    partial void Onid_viajeroChanged();
    partial void Onid_cotizacionChanging(int value);
    partial void Onid_cotizacionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Oncedula_pasaporteChanging(string value);
    partial void Oncedula_pasaporteChanged();
    partial void OnedadChanging(int value);
    partial void OnedadChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public td_viajero()
		{
			this._td_cotizacion = default(EntityRef<td_cotizacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_viajero", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_viajero
		{
			get
			{
				return this._id_viajero;
			}
			set
			{
				if ((this._id_viajero != value))
				{
					this.Onid_viajeroChanging(value);
					this.SendPropertyChanging();
					this._id_viajero = value;
					this.SendPropertyChanged("id_viajero");
					this.Onid_viajeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cotizacion", DbType="Int NOT NULL")]
		public int id_cotizacion
		{
			get
			{
				return this._id_cotizacion;
			}
			set
			{
				if ((this._id_cotizacion != value))
				{
					if (this._td_cotizacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cotizacionChanging(value);
					this.SendPropertyChanging();
					this._id_cotizacion = value;
					this.SendPropertyChanged("id_cotizacion");
					this.Onid_cotizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula_pasaporte", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cedula_pasaporte
		{
			get
			{
				return this._cedula_pasaporte;
			}
			set
			{
				if ((this._cedula_pasaporte != value))
				{
					this.Oncedula_pasaporteChanging(value);
					this.SendPropertyChanging();
					this._cedula_pasaporte = value;
					this.SendPropertyChanged("cedula_pasaporte");
					this.Oncedula_pasaporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int NOT NULL")]
		public int edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(20)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="td_cotizacion_td_viajero", Storage="_td_cotizacion", ThisKey="id_cotizacion", OtherKey="id_cotizacion", IsForeignKey=true)]
		public td_cotizacion td_cotizacion
		{
			get
			{
				return this._td_cotizacion.Entity;
			}
			set
			{
				td_cotizacion previousValue = this._td_cotizacion.Entity;
				if (((previousValue != value) 
							|| (this._td_cotizacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._td_cotizacion.Entity = null;
						previousValue.td_viajeros.Remove(this);
					}
					this._td_cotizacion.Entity = value;
					if ((value != null))
					{
						value.td_viajeros.Add(this);
						this._id_cotizacion = value.id_cotizacion;
					}
					else
					{
						this._id_cotizacion = default(int);
					}
					this.SendPropertyChanged("td_cotizacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tm_moneda")]
	public partial class tm_moneda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_moneda;
		
		private string _codigo;
		
		private string _nombre;
		
		private decimal _tasa_cambio;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntitySet<td_cotizacion> _td_cotizacions;
		
		private EntitySet<td_pago> _td_pagos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_monedaChanging(int value);
    partial void Onid_monedaChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Ontasa_cambioChanging(decimal value);
    partial void Ontasa_cambioChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public tm_moneda()
		{
			this._td_cotizacions = new EntitySet<td_cotizacion>(new Action<td_cotizacion>(this.attach_td_cotizacions), new Action<td_cotizacion>(this.detach_td_cotizacions));
			this._td_pagos = new EntitySet<td_pago>(new Action<td_pago>(this.attach_td_pagos), new Action<td_pago>(this.detach_td_pagos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_moneda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_moneda
		{
			get
			{
				return this._id_moneda;
			}
			set
			{
				if ((this._id_moneda != value))
				{
					this.Onid_monedaChanging(value);
					this.SendPropertyChanging();
					this._id_moneda = value;
					this.SendPropertyChanged("id_moneda");
					this.Onid_monedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tasa_cambio", DbType="Decimal(10,4) NOT NULL")]
		public decimal tasa_cambio
		{
			get
			{
				return this._tasa_cambio;
			}
			set
			{
				if ((this._tasa_cambio != value))
				{
					this.Ontasa_cambioChanging(value);
					this.SendPropertyChanging();
					this._tasa_cambio = value;
					this.SendPropertyChanged("tasa_cambio");
					this.Ontasa_cambioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_moneda_td_cotizacion", Storage="_td_cotizacions", ThisKey="id_moneda", OtherKey="id_moneda")]
		public EntitySet<td_cotizacion> td_cotizacions
		{
			get
			{
				return this._td_cotizacions;
			}
			set
			{
				this._td_cotizacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_moneda_td_pago", Storage="_td_pagos", ThisKey="id_moneda", OtherKey="id_moneda")]
		public EntitySet<td_pago> td_pagos
		{
			get
			{
				return this._td_pagos;
			}
			set
			{
				this._td_pagos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_moneda = this;
		}
		
		private void detach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_moneda = null;
		}
		
		private void attach_td_pagos(td_pago entity)
		{
			this.SendPropertyChanging();
			entity.tm_moneda = this;
		}
		
		private void detach_td_pagos(td_pago entity)
		{
			this.SendPropertyChanging();
			entity.tm_moneda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tm_pais")]
	public partial class tm_pai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pais;
		
		private string _nombre;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntitySet<td_cotizacion> _td_cotizacions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_paisChanging(int value);
    partial void Onid_paisChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public tm_pai()
		{
			this._td_cotizacions = new EntitySet<td_cotizacion>(new Action<td_cotizacion>(this.attach_td_cotizacions), new Action<td_cotizacion>(this.detach_td_cotizacions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pais", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pais
		{
			get
			{
				return this._id_pais;
			}
			set
			{
				if ((this._id_pais != value))
				{
					this.Onid_paisChanging(value);
					this.SendPropertyChanging();
					this._id_pais = value;
					this.SendPropertyChanged("id_pais");
					this.Onid_paisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_pai_td_cotizacion", Storage="_td_cotizacions", ThisKey="id_pais", OtherKey="id_pais_destino")]
		public EntitySet<td_cotizacion> td_cotizacions
		{
			get
			{
				return this._td_cotizacions;
			}
			set
			{
				this._td_cotizacions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_pai = this;
		}
		
		private void detach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_pai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tm_seguro")]
	public partial class tm_seguro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_seguro;
		
		private string _nombre;
		
		private string _descripcion;
		
		private string _cobertura;
		
		private decimal _precio;
		
		private int _duracion;
		
		private System.Nullable<System.DateTime> _creada_en;
		
		private System.Nullable<System.DateTime> _actualizada_en;
		
		private System.Nullable<bool> _flag_activo;
		
		private EntitySet<td_cotizacion> _td_cotizacions;
		
		private EntitySet<td_poliza> _td_polizas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_seguroChanging(int value);
    partial void Onid_seguroChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OncoberturaChanging(string value);
    partial void OncoberturaChanged();
    partial void OnprecioChanging(decimal value);
    partial void OnprecioChanged();
    partial void OnduracionChanging(int value);
    partial void OnduracionChanged();
    partial void Oncreada_enChanging(System.Nullable<System.DateTime> value);
    partial void Oncreada_enChanged();
    partial void Onactualizada_enChanging(System.Nullable<System.DateTime> value);
    partial void Onactualizada_enChanged();
    partial void Onflag_activoChanging(System.Nullable<bool> value);
    partial void Onflag_activoChanged();
    #endregion
		
		public tm_seguro()
		{
			this._td_cotizacions = new EntitySet<td_cotizacion>(new Action<td_cotizacion>(this.attach_td_cotizacions), new Action<td_cotizacion>(this.detach_td_cotizacions));
			this._td_polizas = new EntitySet<td_poliza>(new Action<td_poliza>(this.attach_td_polizas), new Action<td_poliza>(this.detach_td_polizas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_seguro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_seguro
		{
			get
			{
				return this._id_seguro;
			}
			set
			{
				if ((this._id_seguro != value))
				{
					this.Onid_seguroChanging(value);
					this.SendPropertyChanging();
					this._id_seguro = value;
					this.SendPropertyChanged("id_seguro");
					this.Onid_seguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cobertura", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string cobertura
		{
			get
			{
				return this._cobertura;
			}
			set
			{
				if ((this._cobertura != value))
				{
					this.OncoberturaChanging(value);
					this.SendPropertyChanging();
					this._cobertura = value;
					this.SendPropertyChanged("cobertura");
					this.OncoberturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion", DbType="Int NOT NULL")]
		public int duracion
		{
			get
			{
				return this._duracion;
			}
			set
			{
				if ((this._duracion != value))
				{
					this.OnduracionChanging(value);
					this.SendPropertyChanging();
					this._duracion = value;
					this.SendPropertyChanged("duracion");
					this.OnduracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> creada_en
		{
			get
			{
				return this._creada_en;
			}
			set
			{
				if ((this._creada_en != value))
				{
					this.Oncreada_enChanging(value);
					this.SendPropertyChanging();
					this._creada_en = value;
					this.SendPropertyChanged("creada_en");
					this.Oncreada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada_en", DbType="DateTime")]
		public System.Nullable<System.DateTime> actualizada_en
		{
			get
			{
				return this._actualizada_en;
			}
			set
			{
				if ((this._actualizada_en != value))
				{
					this.Onactualizada_enChanging(value);
					this.SendPropertyChanging();
					this._actualizada_en = value;
					this.SendPropertyChanged("actualizada_en");
					this.Onactualizada_enChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag_activo", DbType="Bit")]
		public System.Nullable<bool> flag_activo
		{
			get
			{
				return this._flag_activo;
			}
			set
			{
				if ((this._flag_activo != value))
				{
					this.Onflag_activoChanging(value);
					this.SendPropertyChanging();
					this._flag_activo = value;
					this.SendPropertyChanged("flag_activo");
					this.Onflag_activoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_seguro_td_cotizacion", Storage="_td_cotizacions", ThisKey="id_seguro", OtherKey="id_seguro")]
		public EntitySet<td_cotizacion> td_cotizacions
		{
			get
			{
				return this._td_cotizacions;
			}
			set
			{
				this._td_cotizacions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tm_seguro_td_poliza", Storage="_td_polizas", ThisKey="id_seguro", OtherKey="id_seguro")]
		public EntitySet<td_poliza> td_polizas
		{
			get
			{
				return this._td_polizas;
			}
			set
			{
				this._td_polizas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_seguro = this;
		}
		
		private void detach_td_cotizacions(td_cotizacion entity)
		{
			this.SendPropertyChanging();
			entity.tm_seguro = null;
		}
		
		private void attach_td_polizas(td_poliza entity)
		{
			this.SendPropertyChanging();
			entity.tm_seguro = this;
		}
		
		private void detach_td_polizas(td_poliza entity)
		{
			this.SendPropertyChanging();
			entity.tm_seguro = null;
		}
	}
}
#pragma warning restore 1591
