<?xml version="1.0" encoding="utf-8"?><Database Name="turismoseguro_db" Class="DbLibraryEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=turismoseguroserver2.database.windows.net;Initial Catalog=turismoseguro_db;User ID=grupo1;Connect Timeout=60;Encrypt=True;Trust Server Certificate=False" SettingsObjectName="capaDatos.Properties.Settings" SettingsPropertyName="turismoseguro_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tm_usuarios" Member="tm_usuarios">
    <Type Name="tm_usuario">
      <Column Name="id_usuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="genero" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fecha_nacimiento" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="nacionalidad" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tipo_documento" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="numero_documento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="correo_electronico" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado_cuenta" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tm_usuario_ta_auditoria_dato" Member="ta_auditoria_datos" ThisKey="id_usuario" OtherKey="id_usuario" Type="ta_auditoria_dato" />
      <Association Name="tm_usuario_ta_log" Member="ta_logs" ThisKey="id_usuario" OtherKey="id_usuario" Type="ta_log" />
      <Association Name="tm_usuario_td_compra" Member="td_compras" ThisKey="id_usuario" OtherKey="id_usuario" Type="td_compra" />
      <Association Name="tm_role_tm_usuario" Member="tm_role" ThisKey="id_rol" OtherKey="id_rol" Type="tm_role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ta_auditoria_datos" Member="ta_auditoria_datos">
    <Type Name="ta_auditoria_dato">
      <Column Name="id_auditoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entidad_afectada" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="campo_afectado" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="valor_anterior" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="valor_nuevo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fecha_cambio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tm_usuario_ta_auditoria_dato" Member="tm_usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="tm_usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ta_errores" Member="ta_errores">
    <Type Name="ta_errore">
      <Column Name="id_error" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="modulo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mensaje" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="traza" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="nivel" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ta_logs" Member="ta_logs">
    <Type Name="ta_log">
      <Column Name="id_log" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modulo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="accion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ip_origen" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="fecha_log" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tm_usuario_ta_log" Member="tm_usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="tm_usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.td_compra_servicio_extra" Member="td_compra_servicio_extras">
    <Type Name="td_compra_servicio_extra">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_compra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_servicio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="td_compra_td_compra_servicio_extra" Member="td_compra" ThisKey="id_compra" OtherKey="id_compra" Type="td_compra" IsForeignKey="true" />
      <Association Name="tm_servicios_extra_td_compra_servicio_extra" Member="tm_servicios_extra" ThisKey="id_servicio" OtherKey="id_servicio" Type="tm_servicios_extra" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.td_compras" Member="td_compras">
    <Type Name="td_compra">
      <Column Name="id_compra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_paquete" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_forma_pago" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="estado_pago" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fecha_compra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="td_compra_td_compra_servicio_extra" Member="td_compra_servicio_extras" ThisKey="id_compra" OtherKey="id_compra" Type="td_compra_servicio_extra" />
      <Association Name="td_compra_td_poliza" Member="td_polizas" ThisKey="id_compra" OtherKey="id_compra" Type="td_poliza" />
      <Association Name="tm_usuario_td_compra" Member="tm_usuario" ThisKey="id_usuario" OtherKey="id_usuario" Type="tm_usuario" IsForeignKey="true" />
      <Association Name="tm_formas_pago_td_compra" Member="tm_formas_pago" ThisKey="id_forma_pago" OtherKey="id_forma_pago" Type="tm_formas_pago" IsForeignKey="true" />
      <Association Name="tm_paquete_td_compra" Member="tm_paquete" ThisKey="id_paquete" OtherKey="id_paquete" Type="tm_paquete" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.td_polizas" Member="td_polizas">
    <Type Name="td_poliza">
      <Column Name="id_poliza" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_compra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_cobertura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="numero_poliza" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecha_inicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fecha_fin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="archivo_pdf" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="td_poliza_td_reclamacione" Member="td_reclamaciones" ThisKey="id_poliza" OtherKey="id_poliza" Type="td_reclamacione" />
      <Association Name="td_compra_td_poliza" Member="td_compra" ThisKey="id_compra" OtherKey="id_compra" Type="td_compra" IsForeignKey="true" />
      <Association Name="tm_cobertura_td_poliza" Member="tm_cobertura" ThisKey="id_cobertura" OtherKey="id_cobertura" Type="tm_cobertura" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.td_reclamaciones" Member="td_reclamaciones">
    <Type Name="td_reclamacione">
      <Column Name="id_reclamacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_poliza" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_motivo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="documento" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="estado" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_agente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_reclamo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="td_poliza_td_reclamacione" Member="td_poliza" ThisKey="id_poliza" OtherKey="id_poliza" Type="td_poliza" IsForeignKey="true" />
      <Association Name="tm_agentes_soporte_td_reclamacione" Member="tm_agentes_soporte" ThisKey="id_agente" OtherKey="id_agente" Type="tm_agentes_soporte" IsForeignKey="true" />
      <Association Name="tm_motivos_reclamacion_td_reclamacione" Member="tm_motivos_reclamacion" ThisKey="id_motivo" OtherKey="id_motivo" Type="tm_motivos_reclamacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tm_agentes_soporte" Member="tm_agentes_soportes">
    <Type Name="tm_agentes_soporte">
      <Column Name="id_agente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_agente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="tm_agentes_soporte_td_reclamacione" Member="td_reclamaciones" ThisKey="id_agente" OtherKey="id_agente" Type="td_reclamacione" />
    </Type>
  </Table>
  <Table Name="dbo.tm_ciudades" Member="tm_ciudades">
    <Type Name="tm_ciudade">
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_ciudad" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="id_pais" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tm_ciudade_tm_destino" Member="tm_destinos" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="tm_destino" />
      <Association Name="tm_paise_tm_ciudade" Member="tm_paise" ThisKey="id_pais" OtherKey="id_pais" Type="tm_paise" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tm_coberturas" Member="tm_coberturas">
    <Type Name="tm_cobertura">
      <Column Name="id_cobertura" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_cobertura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="monto_maximo" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="incluye_asistencia" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tm_cobertura_td_poliza" Member="td_polizas" ThisKey="id_cobertura" OtherKey="id_cobertura" Type="td_poliza" />
    </Type>
  </Table>
  <Table Name="dbo.tm_destinos" Member="tm_destinos">
    <Type Name="tm_destino">
      <Column Name="id_destino" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_destino" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_ciudad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="popularidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tm_destino_tm_paquete" Member="tm_paquetes" ThisKey="id_destino" OtherKey="id_destino" Type="tm_paquete" />
      <Association Name="tm_ciudade_tm_destino" Member="tm_ciudade" ThisKey="id_ciudad" OtherKey="id_ciudad" Type="tm_ciudade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tm_formas_pago" Member="tm_formas_pagos">
    <Type Name="tm_formas_pago">
      <Column Name="id_forma_pago" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="metodo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tm_formas_pago_td_compra" Member="td_compras" ThisKey="id_forma_pago" OtherKey="id_forma_pago" Type="td_compra" />
    </Type>
  </Table>
  <Table Name="dbo.tm_motivos_reclamacion" Member="tm_motivos_reclamacions">
    <Type Name="tm_motivos_reclamacion">
      <Column Name="id_motivo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="motivo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="tm_motivos_reclamacion_td_reclamacione" Member="td_reclamaciones" ThisKey="id_motivo" OtherKey="id_motivo" Type="td_reclamacione" />
    </Type>
  </Table>
  <Table Name="dbo.tm_paises" Member="tm_paises">
    <Type Name="tm_paise">
      <Column Name="id_pais" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_pais" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="codigo_iso" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="tm_paise_tm_ciudade" Member="tm_ciudades" ThisKey="id_pais" OtherKey="id_pais" Type="tm_ciudade" />
    </Type>
  </Table>
  <Table Name="dbo.tm_paquetes" Member="tm_paquetes">
    <Type Name="tm_paquete">
      <Column Name="id_paquete" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_paquete" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="duracion_dias" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="precio_base" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id_destino" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipo_paquete" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tm_paquete_td_compra" Member="td_compras" ThisKey="id_paquete" OtherKey="id_paquete" Type="td_compra" />
      <Association Name="tm_destino_tm_paquete" Member="tm_destino" ThisKey="id_destino" OtherKey="id_destino" Type="tm_destino" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tm_roles" Member="tm_roles">
    <Type Name="tm_role">
      <Column Name="id_rol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_rol" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tm_role_tm_usuario" Member="tm_usuarios" ThisKey="id_rol" OtherKey="id_rol" Type="tm_usuario" />
    </Type>
  </Table>
  <Table Name="dbo.tm_servicios_extra" Member="tm_servicios_extras">
    <Type Name="tm_servicios_extra">
      <Column Name="id_servicio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_servicio" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="disponible" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tm_servicios_extra_td_compra_servicio_extra" Member="td_compra_servicio_extras" ThisKey="id_servicio" OtherKey="id_servicio" Type="td_compra_servicio_extra" />
    </Type>
  </Table>
</Database>